from pathlib import Path
from langsmith import traceable
from schemas import plan, state
from schemas.state import State
from schemas.image import GlobalImagePlan
from workflow.settings import llm_planner
from langchain_core.messages import SystemMessage, HumanMessage
import os
import re


def _extract_placeholders(md: str | None) -> set[str]:
    if not md:
        return set()
    return set(re.findall(r"\[\[IMAGE_\d+\]\]", md))


def merge_content(state: State) -> dict:
    
    plan = state["plan"]
    if plan is None:
        raise ValueError("No plan found in state for merging content.")
    ordered_sections = [md for _, md in sorted(state["sections"], key=lambda x: x[0])]
    body = "\n\n".join(ordered_sections).strip()
    merged_md = f"# {plan.blog_title}\n\n{body}\n"
    return {"merged_md": merged_md}


IMAGE_DECISION_PROMPT = """ You are an expert technical editor.
                            Decide if images/diagrams are needed for THIS blog.

                            Rules:
                            - Max 3 images total.
                            - Each image must materially improve understanding (diagram/flow/table-like visual).
                            - Insert placeholders exactly: [[IMAGE_1]], [[IMAGE_2]], [[IMAGE_3]].
                            - If you insert any placeholder, you must return exactly one matching item in images.
                            - Never return placeholders when images=[].
                            - If no images needed: md_with_placeholders must equal input and images=[].
                            - Avoid decorative images; prefer technical diagrams with short labels.
                            Return strictly GlobalImagePlan.
                        """


@traceable(name="image_decision")
def decide_images(state: State) -> dict:
    planner = llm_planner.with_structured_output(GlobalImagePlan)
    merged_md = state.get("merged_md")
    plan = state["plan"]
    
    assert plan is not None

    image_plan = planner.invoke(
        [
            SystemMessage(content=IMAGE_DECISION_PROMPT),
            HumanMessage(
                content=(
                    f"Blog kind: {plan.blog_kind}\n"
                    f"Topic: {plan.blog_title}\n\n"
                    "Insert placeholders + propose image prompts.\n\n"
                    f"Current MD:\n{merged_md}"
                ),
            )
        ]
    )

    md_with_placeholders = image_plan.md_with_placeholders or merged_md
    placeholders_in_md = _extract_placeholders(md_with_placeholders)
    placeholders_in_specs = {img.placeholder for img in image_plan.images}

    if placeholders_in_md != placeholders_in_specs:
        # Fall back to the placeholder-free merged markdown instead of
        # writing a broken document when the planner returns inconsistent output.
        return {
            "md_with_placeholders": merged_md,
            "image_specs": [],
        }

    return {
        "md_with_placeholders": md_with_placeholders,
        "image_specs": [img.model_dump() for img in image_plan.images],
    }

@traceable(name="image_generation")
def _gemini_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Gemini.
    Requires: pip install google-genai
    Env var: GOOGLE_API_KEY
    """
    from google import genai
    from google.genai import types

    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise RuntimeError("GOOGLE_API_KEY is not set.")

    client = genai.Client(api_key=api_key)

    resp = client.models.generate_content(
        model="gemini-3.1-flash-image-preview",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE"],
            safety_settings=[
                types.SafetySetting(
                    category="HARM_CATEGORY_DANGEROUS_CONTENT",
                    threshold="BLOCK_ONLY_HIGH",
                )
            ],
        ),
    )
     # Depending on SDK version, parts may hang off resp.candidates[0].content.parts
    parts = getattr(resp, "parts", None)
    if not parts and getattr(resp, "candidates", None):
        try:
            parts = resp.candidates[0].content.parts
        except Exception:
            parts = None

    if not parts:
        raise RuntimeError("No image content returned (safety/quota/SDK change).")

    for part in parts:
        inline = getattr(part, "inline_data", None)
        if inline and getattr(inline, "data", None):
            return inline.data

    raise RuntimeError("No inline image bytes found in response.")



def _safe_markdown_filename(title: str) -> str:
    # Preserve the human-readable blog title while removing path separators
    # and control characters that would break file creation.
    s = title.strip()
    s = re.sub(r"[\x00-\x1f/]", "", s)
    return s or "blog"


@traceable(name="image_generation_and_placement(reducer)")
def generate_and_place_images(state: State) -> dict:
    plan = state["plan"]
    assert plan is not None

    md = state.get("md_with_placeholders") or state["merged_md"]
    image_specs = state.get("image_specs", []) or []
    filename = f"{_safe_markdown_filename(plan.blog_title)}.md"
    output_dir = Path("output")
    output_dir.mkdir(exist_ok=True)
    output_path = output_dir / filename

    # If the planner did not return usable image specs, fall back to the
    # placeholder-free merged markdown so the output stays valid.
    if not image_specs:
        if _extract_placeholders(md):
            md = state["merged_md"]
        output_path.write_text(md, encoding="utf-8")
        return {"final": md}

    images_dir = output_dir / "images"
    images_dir.mkdir(exist_ok=True)

    for spec in image_specs:
        placeholder = spec["placeholder"]
        filename = spec["filename"]
        out_path = images_dir / filename

        # generate only if needed
        if not out_path.exists():
            try:
                img_bytes = _gemini_generate_image_bytes(spec["prompt"])
                out_path.write_bytes(img_bytes)
            except Exception as e:
                # graceful fallback: keep doc usable
                prompt_block = (
                    f"> **[IMAGE GENERATION FAILED]** {spec.get('caption','')}\n>\n"
                    f"> **Alt:** {spec.get('alt','')}\n>\n"
                    f"> **Prompt:** {spec.get('prompt','')}\n>\n"
                    f"> **Error:** {e}\n"
                )
                md = md.replace(placeholder, prompt_block)
                continue

        img_md = f"![{spec['alt']}](images/{filename})\n*{spec['caption']}*"
        md = md.replace(placeholder, img_md)

    output_path.write_text(md, encoding="utf-8")

    return {"final": md}
